name: Cppcheck
on:
  workflow_call:
jobs:
  docker_check:
    runs-on: [self-hosted, docker, builder]
    container:
      image: ghcr.io/steinwurf/cppcheck-2.8:latest
      options: --user 0:0
      volumes:
        - /home/buildbot/.ssh:/root/.ssh
    name: Cppcheck 2.8
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cppcheck
        uses: deep5050/cppcheck-action@main
